name: cs326
channels:
  - defaults

dependencies:
  - python=3.10
  - requests=2.31.*
  - numpy=1.26.*
  - pandas=2.2.*
  - jupyter
  - pip
  - pip:
    - nbformat==5.10.*
    - pytest==8.1.*
    - datasets==2.18.*
    - plotly==5.20.*
    - scipy==1.12.*
    - scikit-learn==1.3.*
    - matplotlib==3.8.*
    - statsmodels==0.14.*